### ISSUE TITLE
create a project board

### ISSUE THREAD

**Issue by danielhalasz** [lauraramirez220612/TeamFourHYF#15]
https://github.com/HackYourFutureBelgium/incremental-development/blob/master/planning-and-collaborating/7-project-board.md

**Comment by danielhalasz** [comment]
@Senait-coding the cards are actually supposed the be the issues that we have

**Comment by Senait-coding** [comment]
> @Senait-coding the cards are actually supposed the be the issues that we have

@danielhalasz yes I was about to put the issues. I have done it now.thanks,
