### ISSUE TITLE
Creating empty HTML and CSS files

### ISSUE THREAD

**Issue by Moamin-AbuEwaida** [lauraramirez220612/TeamFourHYF#21]
HTML and CSS file needed to be created and left empty till the writing code stage

**Comment by danielhalasz** [comment]
this is a duplicate of the issue
https://github.com/lauraramirez220612/TeamFourHYF/issues/9

**Comment by Moamin-AbuEwaida** [comment]
ooh, I'll close this one then @danielhalasz
