### ISSUE TITLE
Creating an IMAGES folder

### ISSUE THREAD

**Issue by Moamin-AbuEwaida** [lauraramirez220612/TeamFourHYF#24]
to keep all the images of the repo and website in one place, i think this way to keep the repo more organized

**Comment by Senait-coding** [comment]
I will put screenshots of the website inside the image folder

**Comment by Moamin-AbuEwaida** [comment]
awesome
but what do you mean by screenshots ?

**Comment by Senait-coding** [comment]
Screenshot of the website we going to  recreat? Like what we did last time or you have other idea?

**Comment by lauraramirez220612** [comment]
I think it can be or not.
